name: mmg_g
description: MMG G

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_app_check: ^0.0.6+7
  get: ^4.6.1
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  mask_text_input_formatter: ^2.1.0
  connectivity_plus: ^2.2.1
  flutter_speed_dial: ^5.0.0+1
  flutter_typeahead: ^3.2.4
  #fluent_ui: ^3.9.1
  flutter_screenutil: ^5.3.1
  money_input_formatter: ^2.0.0
  #intl_phone_field: ^3.0.1
  url_launcher: ^6.0.20
  fl_chart: ^0.50.0
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons_maker: ^0.10.2
  flutter_native_splash: ^2.1.3+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_rouge.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon_rouge.png
  android: true
  ios: true
  fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icons/

